# Local execution profile for BGEE pipeline
cores: 16                    # Use 16 CPU cores (divided across all jobs)
local-cores: 1               # Cores for the Snakemake process itself (only 1 likely needed)
jobs: 10                     # Maximum concurrent jobs (more concurrent jobs = more resources required)

# Resource limits
resources:
  - mem_mb=102400            # Total/global memory limit in MB (100GB here). 
# Each rule's memory allocation (in config/config.yaml) will still get the listed memory and CPUs per job. New jobs will be queued if they (collectively) exceed this total/global memory limit. 

# Execution settings  
latency-wait: 60             # Wait time for files on distributed filesystems
rerun-incomplete: true       # Automatically rerun incomplete jobs
#printshellcmds: true        # Print shell commands being executed

# Restart settings
restart-times: 3             # Retry failed jobs up to 3 times
