# cluster_config.yaml
# Sets the default parameters to fallback on if not listed for a specific rule.
__default__:
    partition: day
    output: slurm-%j-%x.out
    error: slurm-%j-%x.err
    mem: 4G
    cpus-per-task: 2

# Preprocessing mode == 'merge' (or 'both)
fastp_pe_merge:
    mem: 8G
    cpus-per-task: 8
clean_headers_merge:
    mem: 2G
    cpus-per-task: 4
aggregate_clean_headers_logs_merge:
    mem: 2G
    cpus-per-task: 2

# Preprocessing mode == 'concat' (or 'both)
fastp_pe_concat:
    mem: 2G
    cpus-per-task: 4
fastq_concat:
    mem: 8G
    cpus-per-task: 4
aggregate_concat_logs:
    mem: 2G
    cpus-per-task: 2
quality_trim:
    mem: 4G
    cpus-per-task: 2
aggregate_trim_galore_logs:
    mem: 2G
    cpus-per-task: 2

# MGE 
MitoGeneExtractor_merge:  
    mem: 12G
    cpus-per-task: 8
MitoGeneExtractor_concat:
    mem: 12G
    cpus-per-task: 8

# Postprocessing
rename_and_combine_cons_merge:
    mem: 2G
    cpus-per-task: 4
rename_and_combine_cons_concat: 
    mem: 2G
    cpus-per-task: 4
create_alignment_log_merge:
    mem: 2G
    cpus-per-task: 2
create_alignment_log_concat: 
    mem: 2G
    cpus-per-task: 2

# Fasta cleaner
fasta_cleaner_merge:
    mem: 28G
    cpus-per-task: 24
fasta_cleaner_concat:
    mem: 28G
    cpus-per-task: 24

# Extract statistics
extract_stats_to_csv_merge:  
    mem: 8G
    cpus-per-task: 2
extract_stats_to_csv_concat:
    mem: 8G
    cpus-per-task: 2
combine_stats_files:  
    mem: 1G
    cpus-per-task: 1
    
# Fasta_compare
fasta_compare:
    mem: 8G
    cpus-per-task: 4

# Cleanup
cleanup_files:
    mem: 2G
    cpus-per-task: 2
