# cluster_config.yaml
# Sets the default parameters to fallback on if not listed for a specific rule.
__default__:
    partition: medium
    output: slurm-%j-%x.out
    error: slurm-%j-%x.err
    mem_mb: 4096  # 4G
    cpus-per-task: 2

# Preprocessing mode == 'merge' (or 'both')
fastp_pe_merge:
    mem_mb: 8192  # 8G
    cpus-per-task: 8

clean_headers_merge:
    mem_mb: 2048  # 2G
    cpus-per-task: 4

aggregate_clean_headers_logs_merge:
    mem_mb: 2048  # 2G
    cpus-per-task: 2

# Preprocessing mode == 'concat' (or 'both')
fastp_pe_concat:
    mem_mb: 2048  # 2G
    cpus-per-task: 4

fastq_concat:
    mem_mb: 8192  # 8G
    cpus-per-task: 4

aggregate_concat_logs:
    mem_mb: 2048  # 2G
    cpus-per-task: 2

quality_trim:
    mem_mb: 4096  # 4G
    cpus-per-task: 2

aggregate_trim_galore_logs:
    mem_mb: 2048  # 2G
    cpus-per-task: 2

# MGE 
MitoGeneExtractor_merge:  
    mem_mb: 12288  # 12G
    cpus-per-task: 8

MitoGeneExtractor_concat:
    mem_mb: 12288  # 12G
    cpus-per-task: 8

# Postprocessing
rename_and_combine_cons_merge:
    mem_mb: 2048  # 2G
    cpus-per-task: 4

rename_and_combine_cons_concat: 
    mem_mb: 2048  # 2G
    cpus-per-task: 4

create_alignment_log_merge:
    mem_mb: 2048  # 2G
    cpus-per-task: 2

create_alignment_log_concat: 
    mem_mb: 2048  # 2G
    cpus-per-task: 2

# Fasta cleaner
fasta_cleaner_merge:
    mem_mb: 28672  # 28G
    cpus-per-task: 24

fasta_cleaner_concat:
    mem_mb: 28672  # 28G
    cpus-per-task: 24

# Extract statistics
extract_stats_to_csv_merge:  
    mem_mb: 8192  # 8G
    cpus-per-task: 2

extract_stats_to_csv_concat:
    mem_mb: 8192  # 8G
    cpus-per-task: 2

combine_stats_files:  
    mem_mb: 1024  # 1G
    cpus-per-task: 1
    
# Fasta_compare
fasta_compare:
    mem_mb: 8192  # 8G
    cpus-per-task: 4

# Cleanup
cleanup_files:
    mem_mb: 2048  # 2G
    cpus-per-task: 2
