# BGEE run name identifier
run_name: "run_1"

# Path to MGE installation (MitoGeneExtractor-vX.X.X file)
mge_path: "apps/MitoGeneExtractor-1.9.6beta3/MitoGeneExtractor-v1.9.6beta3"

# Path to samples.csv
samples_file: "path/to/samples.csv"

# Path to references.csv
sequence_reference_file: "path/to/sequence_references.csv"

# Path to output directory. Will make final dir if it does not exist already
output_dir: "path/to/output/dir"



## MGE running parameters (see https://github.com/cmayer/MitoGeneExtractor/tree/main?tab=readme-ov-file#command-line-options)
# Exonerate relative score threshold parameter
r:
  - 1
  - 1.3
  - 1.5
# Exonerate minimum score threshold parameter
s:
  - 50
  - 100
# Number of bp to extend beyond the Exonerate alignment
n: 0
# Genetic code (see https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi)
C: 5
# Consensus threshold (e.g. 0.5 = 50%)
t: 0.5
  
  

# Post-processing of aligned reads for cleaning (using five supplementary scripts)
# human coi filtering -> at content filtering -> statistical outlier filtering -> (optional) reference-base filtering -> 'cleaned' consensus generation

# Default parameters
fasta_cleaner:
  consensus_threshold: 0.5
  human_threshold: 0.95
  at_difference: 0.1
  at_mode: "absolute"
  outlier_percentile: 90.0
  disable_human: false
  disable_at: false
  disable_outliers: false
  reference_dir: null   # To skip reference filtering enter "null"/"None". To enable reference filtering, provide path to a parent directory (flat structure) containing '{sample}_reference.fasta' files.


# Comparison and selection of the 'best' consensus sequence produced by MGE and fasta_cleaner for each sample (using fasta_compare.py)
run_fasta_compare: true  # Set false to skip fasta_compare step

fasta_compare:
  target: "cox1"  # Options: cox1/COI/CO1, rbcl/RBCL, matk/MATK
  verbose: false  # Enable verbose logging (default: false)



# Resource allocation for each rule. Memory shown in Mb (mem_mb), e.g. 2048 = 2G memory.
# Rules have dynamic memory scaling upon retry (mem_mb * retry #).
rules:
  fastp_pe_merge:
    mem_mb: 8192
    threads: 4
   
  clean_headers_merge:
    mem_mb: 4096
    threads: 2
    
  aggregate_clean_headers_logs_merge:
    mem_mb: 2048
    threads: 2
    
  fastp_pe_concat:
    mem_mb: 8192
    threads: 4
    
  fastq_concat:
    mem_mb: 4096
    threads: 4
    
  gzip_trimmed:
    mem_mb: 4096
    threads: 4
    
  aggregate_concat_logs:
    mem_mb: 2048
    threads: 2
    
  quality_trim:
    mem_mb: 8192
    threads: 4
    
  aggregate_trim_galore_logs:
    mem_mb: 2048
    threads: 2
    
  MitoGeneExtractor_merge:
    mem_mb: 20480
    threads: 6
    partition: medium
    
  MitoGeneExtractor_concat:
    mem_mb: 20480
    threads: 6
    partition: medium
    
  rename_and_combine_cons_merge:
    mem_mb: 2048
    threads: 4
    
  rename_and_combine_cons_concat:
    mem_mb: 2048
    threads: 4
    
  create_alignment_log_merge:
    mem_mb: 4096
    threads: 2
    
  create_alignment_log_concat:
    mem_mb: 4096
    threads: 2
    
  human_cox1_filter_merge:
    mem_mb: 10240
    threads: 8
    
  at_content_filter_merge:
    mem_mb: 15360
    threads: 8
    
  statistical_outlier_filter_merge:
    mem_mb: 8192
    threads: 8
    
  reference_filter_merge:
    mem_mb: 8192
    threads: 8
    
  consensus_generation_merge:
    mem_mb: 8192
    threads: 8
    
  aggregate_filter_metrics_merge:
    mem_mb: 2048
    threads: 1

  human_cox1_filter_concat:
    mem_mb: 10240
    threads: 8
  
  at_content_filter_concat:
    mem_mb: 15360
    threads: 8
    
  statistical_outlier_filter_concat:
    mem_mb: 4096
    threads: 1
    
  reference_filter_concat:
    mem_mb: 8192
    threads: 8
    
  consensus_generation_concat:
    mem_mb: 8192
    threads: 8
    
  aggregate_filter_metrics_concat:
    mem_mb: 2048
    threads: 1
    
  extract_stats_to_csv_merge:
    mem_mb: 4096
    threads: 4
    
  extract_stats_to_csv_concat:
    mem_mb: 4096
    threads: 4
    
  combine_stats_files:
    mem_mb: 1024
    threads: 1
    
  fasta_compare:
    mem_mb: 4096
    threads: 4
    
  remove_fasta_cleaner_files:
    mem_mb: 4096
    threads: 4
    
  remove_exonerate_intermediates:
    mem_mb: 4096
    threads: 2
    
  cleanup_files:
    mem_mb: 1024
    threads: 1
