# MGE run name identifier
run_name: "RUN_1"

# Path to MGE installation (MitoGeneExtractor-vX.X.X file)
mge_path: "path/to/MitoGeneExtractor-v1.9.5"

# Path to samples.csv
samples_file: "path/to/samples.csv"

# Path to references.csv
sequence_reference_file: "path/to/sequence_references.csv"

# Path to output directory. Will make final dir if it does not exist already
output_dir: "path/to/output/directory"

## MGE running parameters
# Exonerate relative score threshold parameter
r:
  - 1
  - 1.3
  - 1.5

# Exonerate minimum score threshold parameter
s:
  - 50
  - 100
  
# Post-processing of aligned reads for cleaning (using fasta_cleaner.py)
run_fasta_cleaner: true  # Set false to skip fasta_cleaner step

# Default parameters
fasta_cleaner:
  consensus_threshold: 0.5
  human_threshold: 0.95
  at_difference: 0.1
  at_mode: "absolute"
  outlier_percentile: 90.0
  disable_human: false
  disable_at: false
  disable_outliers: false
  reference_dir: null 

# Comparison of consensus sequences produced via MGE and fasta_cleaner
# Options: cox1/COI/CO1, rbcl/RBCL, matk/MATK
run_fasta_compare: true  # Set false to skip fasta_compare step

fasta_compare:
  target: "cox1"
  verbose: false
