# profiles/slurm/config.yaml

executor: slurm

default-resources:
  - slurm_partition=[PARITION]
  - slurm_extra="--ntasks=1 --signal=USR2@90 --no-requeue"
    # --no-requeue: Prevents the job from being automatically requeued if it fails (clashes with snakemake retry memory scaling)
    # --signal=USR2@90: Sets up a signal to be sent to the job when it approaches its time limit.
    # --ntasks=1: Number of parallel MPI tasks. I.e. Each job in the workflow is considered by SLURM to be 1 task.
  
jobs: 15                          # Maximum number of concurrent jobs run on cluster.
latency-wait: 90                  # Wait N seconds before checking job status
local-cores: 4                    # N cores for internal snakemake operations.
max-jobs-per-second: 1            # Controls rate Snakemake submits jobs to SLURM. Prevents overwhelming scheduler.
max-status-checks-per-second: 0.1 # Controls how often Snakemake polls SLURM to check the status of submitted jobs.
